### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by Xpression1337** [rdinit/Discord-RPC-for-WarThunder#1]
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    set_status()
  File "main.py", line 93, in set_status
    wt.update_msg(last_dmg=last_dmg)
NameError: name 'last_dmg' is not defined

**Comment by rdinit** [comment]
Please, write feedback. Unfortunately, I can't fully test the performance right now. I think now it should work.

> Traceback (most recent call last): File "main.py", line 144, in set_status() File "main.py", line 93, in set_status wt.update_msg(last_dmg=last_dmg) NameError: name 'last_dmg' is not defined
